-- Categories
create table if not exists categories (
  id bigint generated by default as identity primary key,
  name text unique not null
);

-- Questions
create table if not exists questions (
  id bigint generated by default as identity primary key,
  type text not null check (type in ('multiple-choice','long-answer')),
  text text not null,
  options jsonb, -- array of strings when type='multiple-choice'
  correct_answer text, -- e.g., 'A'
  difficulty text default 'medium',
  reference text,
  image_url text,
  code text
);

-- Question categories (many-to-many)
create table if not exists question_categories (
  question_id bigint references questions(id) on delete cascade,
  category_name text references categories(name) on delete cascade,
  primary key (question_id, category_name)
);

-- Students
create table if not exists students (
  id text primary key,
  name text not null,
  password text not null
);

-- Tests
create table if not exists tests (
  id bigint generated by default as identity primary key,
  name text not null,
  duration integer not null, -- minutes
  created_at timestamptz default now()
);

-- Test questions (snapshot of a question at test creation)
create table if not exists test_questions (
  test_id bigint references tests(id) on delete cascade,
  question_index integer not null, -- index within the test
  question jsonb not null, -- store the question payload as JSON to freeze state at creation time
  primary key (test_id, question_index)
);

-- Test assignment
create table if not exists test_assignments (
  test_id bigint references tests(id) on delete cascade,
  student_id text references students(id) on delete cascade,
  primary key (test_id, student_id)
);

-- Submissions
create table if not exists submissions (
  id bigint generated by default as identity primary key,
  test_id bigint references tests(id) on delete cascade,
  student_id text references students(id) on delete cascade,
  submitted_at timestamptz default now()
);

-- Submission answers
create table if not exists submission_answers (
  submission_id bigint references submissions(id) on delete cascade,
  question_index integer not null,
  question text not null, -- question text for review UI
  type text not null check (type in ('multiple-choice','long-answer')),
  answer text,
  correct boolean,
  reviewed boolean default false,
  comment text,
  primary key (submission_id, question_index)
);